version: '3'
services:
  playlister-activity-db:
    image: "mysql"
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=activities
  playlister-activity-elasticsearch:
    image: "elasticsearch"
    ports: 
      - 9200:9200
      - 9300:9300